# Generated by Django 2.2.3 on 2020-02-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginintime', models.DateTimeField(verbose_name='login in time')),
                ('lastLogouttime', models.DateTimeField(verbose_name='last login out time')),
                ('onlinetime', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netBarSys.Users')),
            ],
        ),
    ]
