# Generated by Django 2.2.3 on 2020-02-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netBarSys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfos',
            name='loginintime',
        ),
        migrations.AddField(
            model_name='userinfos',
            name='logintime',
            field=models.DateTimeField(default='1920-01-01 00:00:00', verbose_name='login in time'),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='lastLogouttime',
            field=models.DateTimeField(default='1920-01-01 00:00:00', verbose_name='last login out time'),
        ),
    ]
