# Generated by Django 2.2.3 on 2020-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netBarSys', '0004_userinfos_onlinetimestr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='onlinetimestr',
            field=models.CharField(default='不到1分钟', max_length=50),
        ),
    ]
